name: usb_device
description: Flutter plugin for connecting/accessing usb device.
version: 0.0.2
repository: https://github.com/Apparence-io/webUSB_plugin/


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  usb_device_web: ^0.0.1
  usb_device_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        default_package: usb_device_web
